services:
  users_app:
    build: .
    container_name: users_app
    command: bash -c "python3 ./django/app/vault/vault_init.py"
    restart: always
    environment:
      - VAULT_DATABASE_NAME=users_db
    volumes:
      - .:/usr/src/app/django
      - ../vault/data:/usr/src/app/vault/
    networks:
      - website-network
      - users-network
    depends_on:
      users_db:
        condition: service_healthy
  users_db:
    image: postgres:16
    container_name: users_db
    restart: always
    volumes:
      - users_db:/var/lib/postgresql/data/
    networks:
      - users-network
      - vault-network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  users_db:

networks:
  website-network:
    name: website_network
  users-network:
    name: users_network
  vault-network:
    name: vault_network